### ISSUE TITLE
help build

### ISSUE THREAD

**Issue by woshishiq1** [qiabug/qiapiao#1]
编译出来试试效果呀

**Comment by qiabug** [comment]
[Releasephysx27.zip](https://github.com/qiabug/qiapiao/files/9961840/Releasephysx27.zip)

**Comment by woshishiq1** [comment]
> [发布physx27.zip](https://github.com/qiabug/qiapiao/files/9961840/Releasephysx27.zip)

  刚刚测试了一下，没什么问题。感谢为卡友提供良好游戏体验
