### ISSUE TITLE
能教一教怎么编译这个dll吗

### ISSUE THREAD

**Issue by woshishiq1** [qiabug/qiapiao#11]
11

**Comment by qiabug** [comment]
用 [Visual Studio](https://visualstudio.microsoft.com/) 编译

**Comment by woshishiq1** [comment]
我说的详细步骤，都运行什么命令，这个不能用github ac打包吗

**Comment by qiabug** [comment]
我也不知道具体运行了什么命令, 但如果你想编译它, 请使用`Visual Studio`打开`.sln`文件, 然后在菜单栏点击`生成->生成解决方案`即可.

**Comment by woshishiq1** [comment]
装了Visual Studio编译成功了！这特征码是自动检索更新吗！还是要你在github更新才行
