### ISSUE TITLE
新版本开始失效了

### ISSUE THREAD

**Issue by woshishiq1** [qiabug/qiapiao#8]
出来更新下吧，新版本失效了

**Comment by qiabug** [comment]
这个插件最后支持的版本是【龙晶大闯关】Beta82 Build30，可以去玩单机或私服。对于官方服请移步至更成熟的 [StyGame/kapiao](https://github.com/StyGame/kapiao)

**Comment by woshishiq1** [comment]
我都以为你把github账号忘了呢0 0！
